POST http://localhost:5000/api/v1/products HTTP/1.1
Content-Type: application/json

{
	"name": "Hungarian Horntail",
	"price": 499,
	"quantity": 1,
  "isAvailable": true
}
###
POST http://localhost:5000/api/v1/users
Content-Type: application/json

{
  "username": "tester",
  "email": "test@test.com",
  "password": "test1234",
  "firstName": "Testing",
  "lastName": "Tester",
  "isAdmin": false,
  "isOwner": true
}

###
GET http://localhost:5000/api/v1/users/6227c8238c9dcf12d44e96d7

###
GET http://localhost:5000/api/v1/products/6227e134ff6b594dd8dd6d89


