POST http://localhost:5000/api/v1/expense HTTP/1.1
Content-Type: application/json

{
	"name": "Lunch",
	"amount": 19,
  "tag": "Food"
}
###
POST http://localhost:5000/api/v1/users/
Content-Type: application/json

{
  "username": "testaccount",
  "email": "tester@test.com",
  "password": "test1234",
  "firstName": "random",
  "lastName": "dude",
  "isAdmin": false
}

###
GET http://localhost:5000/api/v1/users/62347a7ee8e4d435086cb497
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjM0N2E3ZWU4ZTRkNDM1MDg2Y2I0OTciLCJlbWFpbCI6InNlYmFzdGlhbkB0ZXN0LmlvIiwiaWF0IjoxNjQ3NzMwNjIzLCJleHAiOjE2NDc3MzQyMjN9.npTwsz-6i0LD5rucz-oii4aqhkdj4jpmftMr0tXtQpQ

###
PUT http://localhost:5000/api/v1/users/6228d144f5eadd480c9b93ce
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjI4ZDE0NGY1ZWFkZDQ4MGM5YjkzY2UiLCJlbWFpbCI6InNlYmFzdGlhbkB0ZXN0LmlvIiwiaWF0IjoxNjQ3NTk2NjQwLCJleHAiOjE2NDc2MDAyNDB9.wnbDgFBCnZBFfa-fGAIrpI0ZBZDCgaRDqhVeKy3Gi1w
Content-Type: application/json

{
"firstName": "Sebo"
}
###
GET http://localhost:5000/api/v1/budget/

###
POST  http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
      "email": "sebastian@test.io",
  		"password": "test1234"
  }

###
PATCH http://localhost:5000/api/v1/users/addExpense/6228d144f5eadd480c9b93ce/62308295a560b012b459a023
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjI4ZDE0NGY1ZWFkZDQ4MGM5YjkzY2UiLCJlbWFpbCI6InNlYmFzdGlhbkB0ZXN0LmlvIiwiaWF0IjoxNjQ3NDUxNDIwLCJleHAiOjE2NDc0NTUwMjB9.CgAikYUPBCt-DJ6tE4TAtx0GCRCbwKG4dt2jWJJOoec
Content-Type: application/json



### 
DELETE http://localhost:5000/api/v1/products/6228aecc4c63fd6d68a926e5